 Resource requests & Limits:
 
 Syn:
 
 resources:
   requests:      # minimum guarenty cpu ,memory avilable Pod
     memory: 64Mi
     cpu: 200m
   limits:       #  upto utilize this resources
     cpu: 500m
     memory: 512Mi	 
---	 
   	 resources:
       requests:
         cpu: 1
         memory: 2Gi
       limits:	
        cpu: 1
        memory: 4Gi
 
 Resource reuests should be less than or equal to resource limits.

 Exapmple:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavnewebappdeployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: mavenweapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebapp
        image: vaddevenkat/maven-web-application:1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
spec:
  selector:
    app: mavenwebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080

