apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapps
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      name: springapp
  template:
    metadata:
      name: springapppod
      labels:
        name: springapp
    spec:
      containers:
      - name:  springappcontainer
        image: vaddevenkat/springboot-application:1
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: 500Mi
            cpu: 500M
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongodbsvc
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb123
---
apiVersion: v1
kind: Service
metadata:
  name: springappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    name: springapp
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1  
kind: ReplicaSet
metadata:
  name:  mongodb
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodbpod
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodbcontainer
        image:  mongo
        ports:
          - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: devdb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: devdb123
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbsvc
  namespace: test-ns
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017


# 
    







